---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.13.1 에는 새로운 향상 기능이 포함되어 있습니다. 
---
= Cloud Volumes ONTAP 9.13.1 의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.13.1 에는 새로운 개선 사항이 포함되어 있습니다.

최신 버전의 BlueXP에는 추가 기능 및 향상된 기능이 도입되었습니다. 를 참조하십시오 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP 릴리스 정보"^] 를 참조하십시오.



== 9.13.1 P14(2025년 4월 17일)

이제 모든 클라우드 공급자에 대해 Cloud Volumes ONTAP에서 9.13.1 P14 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P14["P14 패치에서 수정된 버그 목록을 봅니다"^] (NetApp 지원 사이트에 로그인 필요).



== 9.13.1 P13(2025년 1월 20일)

이제 모든 클라우드 공급자에 대해 Cloud Volumes ONTAP에서 9.13.1 P13 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P13["P13 패치에서 수정된 버그 목록을 봅니다"^] (NetApp 지원 사이트에 로그인 필요).



== 9.13.1 P12(2024년 11월 25일)

이제 모든 클라우드 공급자에 대해 Cloud Volumes ONTAP에서 9.13.1 P12 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P12["P12 패치에서 수정된 버그 목록을 봅니다"^] (NetApp 지원 사이트에 로그인 필요).



== 9.13.1 P11(2024년 10월 14일)

이제 모든 클라우드 공급자에 대해 Cloud Volumes ONTAP에서 9.13.1 P11 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P11["P11 패치에서 수정된 버그 목록을 봅니다"^] (NetApp 지원 사이트에 로그인 필요).



== 9.13.1 P10(2024년 8월 8일)

이제 모든 클라우드 공급자에 대해 Cloud Volumes ONTAP에서 9.13.1 P10 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P10["P10 패치에서 수정된 버그 목록을 봅니다"^] (NetApp 지원 사이트에 로그인 필요).



== 9.13.1 P9(2024년 5월 22일)

이제 모든 클라우드 공급자를 위해 Cloud Volumes ONTAP에서 9.13.1 P9 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P9["P9 패치에서 수정된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.13.1 P8(2024년 4월 18일)

이제 모든 클라우드 제공업체가 Cloud Volumes ONTAP에서 9.13.1 P8 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P8["P8 패치에서 수정된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.13.1 P7(2024년 4월 1일)

이제 모든 클라우드 제공업체가 Cloud Volumes ONTAP에서 9.13.1 P7 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P7["P7 패치에서 수정된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.13.1 P6(2024년 2월 5일)

이제 모든 클라우드 공급자를 위해 Cloud Volumes ONTAP에서 9.13.1 P6 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P6["P6 패치에서 수정된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.13.1 P4(2023년 12월 8일)

이제 모든 클라우드 공급자가 Cloud Volumes ONTAP에서 9.13.1 P4 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P4["P4 패치에서 수정된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.13.1 P2 및 9.13.1 P3(2023년 10월 20일)

3.9.26 이상을 실행하는 커넥터가 있는 경우 이제 모든 클라우드 공급자에 대해 9.13.1 P2 및 9.13.1 P3 패치를 Cloud Volumes ONTAP에서 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

* link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P3["P3 패치에서 수정된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).
* link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P2["P2 패치에서 수정된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).




== 9.13.1 P1(2023년 10월 3일)

3.9.26 이상을 실행하는 커넥터가 있는 경우 이제 모든 클라우드 공급자에 대해 Cloud Volumes ONTAP 9.13.1 P1 패치를 사용할 수 있습니다. BlueXP는 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P1["P1 패치에서 수정된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.13.1 GA(2023년 7월 26일)

Cloud Volumes ONTAP 9.13.1 의 일반 가용성 릴리스는 현재 AWS, Azure 및 Google Cloud에서 사용할 수 있습니다.



== 9.13.1 RC1(2023년 6월 26일)

Cloud Volumes ONTAP 9.13.1 출시 후보 1은 현재 AWS, Azure 및 Google Cloud에서 사용할 수 있습니다.

FabricPool의 몇 가지 성능 향상이 Cloud Volumes ONTAP의 계층형 데이터에 영향을 미칠 수 있습니다.

.순차적 읽기 속도 및 계층화 개선
FabricPool의 향상된 읽기 성능 및 계층화 처리량으로 인해 온프레미스 오브젝트 저장소와 `PUT` 작업의 비율이 높을 수 있습니다 `GET`. 원활한 성능을 위한 충분한 성능 여유를 확보하십시오.

자세한 내용은 를 참조하십시오 https://www.netapp.com/media/17239-tr-4598.pdf["FabricPool 모범 사례 가이드 를 참조하십시오"^]

.적극적인 미리 읽기 기능
 `Aggressive Readahead`FabricPool의 기능은 파일 수준에서 읽기 작업을 늘려 퍼블릭 클라우드의 읽기 비용과 메모리 활용률을 높일 수 있습니다.

자세한 내용은 다음 ONTAP 설명서를 참조하십시오. https://docs.netapp.com/us-en/ontap/fabricpool/enable-disable-aggressive-read-ahead-task.html#enable-aggressive-read-ahead-mode-during-volume-creation["적극적인 미리 읽기 모드를 활성화 및 비활성화합니다"^]

.클라우드 쓰기 기능
이 기능을 통해 NFS 클라이언트는 FabricPool의 용량 계층에 직접 쓸 수 있습니다. 이 기능은 특정 제한 사항이 있으므로 주의해서 사용해야 합니다. 예를 들어 SnapMirror와 같은 일반 ONTAP 트래픽에 클라우드 쓰기 NFS 트래픽이 추가되는 경우 SnapMirror의 전체 RPO(복구 시점 목표) 및 RTO(복구 시간 목표)가 영향을 받을 수 있습니다.

자세한 내용은 다음 ONTAP 설명서를 참조하십시오. https://docs.netapp.com/us-en/ontap/fabricpool/enable-disable-volume-cloud-write-task.html["볼륨을 클라우드에 직접 쓰도록 설정 및 해제합니다"^]



== 노트 업그레이드

이 릴리스 업그레이드에 대한 자세한 내용은 이 노트를 참조하십시오.



=== 업그레이드 방법

Cloud Volumes ONTAP 업그레이드는 BlueXP에서 완료해야 합니다. System Manager 또는 CLI를 사용하여 Cloud Volumes ONTAP를 업그레이드해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 줄 수 있습니다.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXP에서 알림을 받을 때 업그레이드하는 방법에 대해 알아봅니다"^].



=== 지원되는 업그레이드 경로입니다

9.12.1 및 9.13.0 릴리스에서 Cloud Volumes ONTAP 9.13.1 로 업그레이드할 수 있습니다. BlueXP에서 해당 Cloud Volumes ONTAP 시스템을 이 릴리즈로 업그레이드하라는 메시지가 표시됩니다.



=== 커넥터의 필수 버전입니다

새로운 Cloud Volumes ONTAP 9.13.1 시스템을 배포하고 기존 시스템을 9.13.1 버전으로 업그레이드하려면 BlueXP 커넥터 버전이 3.9.26 이상이어야 합니다.


TIP: Connector의 자동 업그레이드는 기본적으로 활성화되어 있으므로 최신 버전을 실행해야 합니다.



=== 알아 보십시오

* 단일 노드 시스템을 업그레이드하면 시스템이 최대 25분 동안 오프라인 상태로 전환되고 이 동안 I/O가 중단됩니다.
* HA 2노드 업그레이드는 무중단으로 I/O를 업그레이드할 수 있으며 이 무중단 업그레이드 프로세스 중에 각 노드가 동시 업그레이드되어 클라이언트에 I/O를 계속 제공합니다.




=== C4, M4 및 R4 인스턴스는 더 이상 지원되지 않습니다

AWS에서 C4, M4 및 R4 EC2 인스턴스 유형은 더 이상 Cloud Volumes ONTAP에서 지원되지 않습니다. C4, M4 또는 R4 인스턴스 유형에서 실행 중인 기존 시스템이 있는 경우 C5, M5 또는 R5 인스턴스 제품군의 인스턴스 유형으로 변경해야 합니다. 인스턴스 유형을 변경하기 전에는 이 릴리즈로 업그레이드할 수 없습니다.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP의 EC2 인스턴스 유형을 변경하는 방법에 대해 알아보십시오"^].

을 참조하십시오 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp 지원"^] 이러한 인스턴스 유형의 가용성 및 지원에 대한 자세한 내용을 보려면 를 참조하십시오.
